package coordinador;


/**
* coordinador/Archivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 14 de mayo de 2010 11H07' CEST
*/


// Creado por el coordinador. Mantiene información de los archivos de la red.
public interface Archivo extends ArchivoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Archivo
