package coordinador;


/**
* coordinador/ArchivoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 11 de mayo de 2010 21H59' CEST
*/


// Creado por el coordinador. Mantiene información de los archivos de la red.
public interface ArchivoOperations 
{
  String nombre ();
  int tam ();
  long checksum ();
  void insertarSeed (int id, String ref);
  void insertarPeer (int id, String ref);
  void eliminarSeed (int id);
  void eliminarPeer (int id);
  String[] getSeeds ();
  String[] getPeers ();
} // interface ArchivoOperations
