package coordinador;


/**
* coordinador/CoordinadorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 6 de mayo de 2010 14H48' CEST
*/

public abstract class CoordinadorPOA extends org.omg.PortableServer.Servant
 implements coordinador.CoordinadorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("muestra", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // coordinador/Coordinador/login
       {
         archivo.Archivo as[] = archivo.archivosHelper.read (in);
         this.login (as);
         out = $rh.createReply();
         break;
       }

       case 1:  // coordinador/Coordinador/muestra
       {
         this.muestra ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:coordinador/Coordinador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Coordinador _this() 
  {
    return CoordinadorHelper.narrow(
    super._this_object());
  }

  public Coordinador _this(org.omg.CORBA.ORB orb) 
  {
    return CoordinadorHelper.narrow(
    super._this_object(orb));
  }


} // class CoordinadorPOA
