/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteP2P.java
 *
 * Created on 09-may-2010, 2:47:04
 */

package gui;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;


/**
 *
 * @author sema
 */
public class ClienteP2P extends javax.swing.JFrame {

    private DefaultListModel modeloListaRecursos = new DefaultListModel();
    private Buscando hilo;
    private Worker w;

    /** Creates new form ClienteP2P */
    public ClienteP2P() {
        initComponents();

        // Otras inicializaciones
        loaderBuscando.setVisible(false);
        //panelNuevaBusqueda.remove(loaderBuscando);

         hilo = new Buscando(loaderBuscando, panelNuevaBusqueda);
         w = new Worker(loaderBuscando);

        // Cargar desde el fichero XML, la lista de ficheros/recursos compartidos
        //

        // Para el JList
        listaFicherosCompartidos.setModel(modeloListaRecursos);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPpal = new javax.swing.JPanel();
        barraHerramientas = new javax.swing.JToolBar();
        iconConectar = new javax.swing.JButton();
        iconDesconectar = new javax.swing.JButton();
        separador1 = new javax.swing.JToolBar.Separator();
        iconLimpiarResultados = new javax.swing.JButton();
        iconDescargar = new javax.swing.JButton();
        iconLimpiarDescargas = new javax.swing.JButton();
        separador2 = new javax.swing.JToolBar.Separator();
        iconAyuda = new javax.swing.JButton();
        iconSalir = new javax.swing.JButton();
        pestanyasApp = new javax.swing.JTabbedPane();
        pestaniaBiblioteca = new javax.swing.JPanel();
        panelMiBiblio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFicherosCompartidos = new javax.swing.JList();
        panelAniadirFichero = new javax.swing.JPanel();
        anyadirRecurso = new javax.swing.JLabel();
        quitarRecurso = new javax.swing.JLabel();
        actualizarBiblioteca = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        panelNuevaBusqueda = new javax.swing.JPanel();
        labelFicheroBuscar = new javax.swing.JLabel();
        cajaTextoNomFich = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        loaderBuscando = new javax.swing.JLabel();
        panelResultadosBusqueda = new javax.swing.JPanel();
        scrollPaneResultados = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        pestaniaDescargas = new javax.swing.JPanel();
        panelDescargas = new javax.swing.JPanel();
        scrollPaneDescargas = new javax.swing.JScrollPane();
        tableDescargas = new javax.swing.JTable();
        menuPpal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionArchivoLogin = new javax.swing.JMenuItem();
        opcionArchivoLogout = new javax.swing.JMenuItem();
        separadorArchivo = new javax.swing.JPopupMenu.Separator();
        opcionArchivoSalir = new javax.swing.JMenuItem();
        menuP2PSF = new javax.swing.JMenu();
        opcionP2PBiblioteca = new javax.swing.JMenuItem();
        opcionP2PBusqueda = new javax.swing.JMenuItem();
        opcionP2PDescargas = new javax.swing.JMenuItem();
        separadorP2PSF = new javax.swing.JPopupMenu.Separator();
        opcionP2PLimpiarResultados = new javax.swing.JMenuItem();
        opcionP2PLimpiarDescargas = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        ayudaAyuda = new javax.swing.JMenuItem();
        ayudaAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente de redes P2P");
        setMinimumSize(new java.awt.Dimension(400, 600));
        setResizable(false);

        panelPpal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);
        barraHerramientas.setBorderPainted(false);

        iconConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/conectar.png"))); // NOI18N
        iconConectar.setToolTipText("Conectarse a la red P2PSF");
        iconConectar.setFocusable(false);
        iconConectar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconConectar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconConectarActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconConectar);

        iconDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/desconectar.png"))); // NOI18N
        iconDesconectar.setToolTipText("Desconectarse de la red P2PSF");
        iconDesconectar.setFocusable(false);
        iconDesconectar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconDesconectar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconDesconectarActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconDesconectar);
        barraHerramientas.add(separador1);

        iconLimpiarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/limpiarBusqueda.png"))); // NOI18N
        iconLimpiarResultados.setToolTipText("Limpiar los resultados de la búsqueda");
        iconLimpiarResultados.setFocusable(false);
        iconLimpiarResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconLimpiarResultados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconLimpiarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconLimpiarResultadosActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconLimpiarResultados);

        iconDescargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/descargar.png"))); // NOI18N
        iconDescargar.setToolTipText("Ir a la pestaña Descargas");
        iconDescargar.setFocusable(false);
        iconDescargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconDescargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconDescargarActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconDescargar);

        iconLimpiarDescargas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/limpiarDescargas.png"))); // NOI18N
        iconLimpiarDescargas.setToolTipText("Limpiar descargas");
        iconLimpiarDescargas.setFocusable(false);
        iconLimpiarDescargas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconLimpiarDescargas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconLimpiarDescargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconLimpiarDescargasActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconLimpiarDescargas);
        barraHerramientas.add(separador2);

        iconAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/ayuda.png"))); // NOI18N
        iconAyuda.setToolTipText("Ayuda");
        iconAyuda.setFocusable(false);
        iconAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconAyuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconAyudaActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconAyuda);

        iconSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/salir.png"))); // NOI18N
        iconSalir.setToolTipText("Salir de la aplicación... ¿Seguro?");
        iconSalir.setFocusable(false);
        iconSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconSalirActionPerformed(evt);
            }
        });
        barraHerramientas.add(iconSalir);

        panelMiBiblio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Ficheros compartidos actualmente (Mi Biblioteca)"));

        listaFicherosCompartidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaFicherosCompartidos);

        javax.swing.GroupLayout panelMiBiblioLayout = new javax.swing.GroupLayout(panelMiBiblio);
        panelMiBiblio.setLayout(panelMiBiblioLayout);
        panelMiBiblioLayout.setHorizontalGroup(
            panelMiBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMiBiblioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMiBiblioLayout.setVerticalGroup(
            panelMiBiblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMiBiblioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAniadirFichero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opciones de compartición"));

        anyadirRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/anyadirFichero.png"))); // NOI18N
        anyadirRecurso.setText("Añadir un nuevo recurso a \"Mi Biblioteca\"");
        anyadirRecurso.setToolTipText("Añade un nuevo fichero (o ficheros) del disco local a Mi Biblioteca");
        anyadirRecurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anyadirRecursoMouseClicked(evt);
            }
        });

        quitarRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/quitarFichero.png"))); // NOI18N
        quitarRecurso.setText("Quitar los recursos seleccionados");
        quitarRecurso.setToolTipText("Quita el o los recursos compartidos que se encuentren seleccionados en \"Mi Biblioteca\"");
        quitarRecurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarRecursoMouseClicked(evt);
            }
        });

        actualizarBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/actualizarBiblioteca.png"))); // NOI18N
        actualizarBiblioteca.setText("Actualizar \"Mi Biblioteca\" en la red P2PSF");
        actualizarBiblioteca.setToolTipText("Hace efectivos los cambios realizados en \"Mi Biblioteca\" para la red P2P");
        actualizarBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarBibliotecaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAniadirFicheroLayout = new javax.swing.GroupLayout(panelAniadirFichero);
        panelAniadirFichero.setLayout(panelAniadirFicheroLayout);
        panelAniadirFicheroLayout.setHorizontalGroup(
            panelAniadirFicheroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAniadirFicheroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelAniadirFicheroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAniadirFicheroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(actualizarBiblioteca))
                    .addComponent(quitarRecurso)
                    .addComponent(anyadirRecurso))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelAniadirFicheroLayout.setVerticalGroup(
            panelAniadirFicheroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAniadirFicheroLayout.createSequentialGroup()
                .addComponent(anyadirRecurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitarRecurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualizarBiblioteca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pestaniaBibliotecaLayout = new javax.swing.GroupLayout(pestaniaBiblioteca);
        pestaniaBiblioteca.setLayout(pestaniaBibliotecaLayout);
        pestaniaBibliotecaLayout.setHorizontalGroup(
            pestaniaBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaniaBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMiBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAniadirFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pestaniaBibliotecaLayout.setVerticalGroup(
            pestaniaBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaniaBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pestaniaBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelAniadirFichero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMiBiblio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pestanyasApp.addTab("Biblioteca de archivos compartidos", pestaniaBiblioteca);

        panelNuevaBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Realizar nueva búsqueda"));

        labelFicheroBuscar.setText("Nombre del fichero a buscar:");

        botonBuscar.setText("¡Búscalo!");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        loaderBuscando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/buscando.gif"))); // NOI18N
        loaderBuscando.setText("Buscando...");

        javax.swing.GroupLayout panelNuevaBusquedaLayout = new javax.swing.GroupLayout(panelNuevaBusqueda);
        panelNuevaBusqueda.setLayout(panelNuevaBusquedaLayout);
        panelNuevaBusquedaLayout.setHorizontalGroup(
            panelNuevaBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFicheroBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaTextoNomFich, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar)
                .addGap(60, 60, 60)
                .addComponent(loaderBuscando)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelNuevaBusquedaLayout.setVerticalGroup(
            panelNuevaBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNuevaBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFicheroBuscar)
                    .addComponent(cajaTextoNomFich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaderBuscando)
                    .addComponent(botonBuscar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelResultadosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Resultados de la búsqueda"));

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneResultados.setViewportView(tablaResultados);

        javax.swing.GroupLayout panelResultadosBusquedaLayout = new javax.swing.GroupLayout(panelResultadosBusqueda);
        panelResultadosBusqueda.setLayout(panelResultadosBusquedaLayout);
        panelResultadosBusquedaLayout.setHorizontalGroup(
            panelResultadosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelResultadosBusquedaLayout.setVerticalGroup(
            panelResultadosBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelResultadosBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNuevaBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNuevaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultadosBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestanyasApp.addTab("Búsquedas", panelBusqueda);

        panelDescargas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Descargas"));

        tableDescargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneDescargas.setViewportView(tableDescargas);

        javax.swing.GroupLayout panelDescargasLayout = new javax.swing.GroupLayout(panelDescargas);
        panelDescargas.setLayout(panelDescargasLayout);
        panelDescargasLayout.setHorizontalGroup(
            panelDescargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescargasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneDescargas, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDescargasLayout.setVerticalGroup(
            panelDescargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescargasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneDescargas, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pestaniaDescargasLayout = new javax.swing.GroupLayout(pestaniaDescargas);
        pestaniaDescargas.setLayout(pestaniaDescargasLayout);
        pestaniaDescargasLayout.setHorizontalGroup(
            pestaniaDescargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaniaDescargasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescargas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pestaniaDescargasLayout.setVerticalGroup(
            pestaniaDescargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaniaDescargasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescargas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestanyasApp.addTab("Descargas", pestaniaDescargas);

        javax.swing.GroupLayout panelPpalLayout = new javax.swing.GroupLayout(panelPpal);
        panelPpal.setLayout(panelPpalLayout);
        panelPpalLayout.setHorizontalGroup(
            panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestanyasApp, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
            .addComponent(barraHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        panelPpalLayout.setVerticalGroup(
            panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPpalLayout.createSequentialGroup()
                .addComponent(barraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pestanyasApp, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuArchivo.setText("Archivo");

        opcionArchivoLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        opcionArchivoLogin.setText("Conectar...");
        opcionArchivoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionArchivoLoginActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionArchivoLogin);

        opcionArchivoLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        opcionArchivoLogout.setText("Desconectar...");
        opcionArchivoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionArchivoLogoutActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionArchivoLogout);
        menuArchivo.add(separadorArchivo);

        opcionArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        opcionArchivoSalir.setText("Salir");
        opcionArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionArchivoSalir);

        menuPpal.add(menuArchivo);

        menuP2PSF.setText("P2PSF");

        opcionP2PBiblioteca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        opcionP2PBiblioteca.setText("Mi Biblioteca");
        opcionP2PBiblioteca.setToolTipText("Muestra la ventana correspondiente a los archivos actualmente compartidos");
        opcionP2PBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionP2PBibliotecaActionPerformed(evt);
            }
        });
        menuP2PSF.add(opcionP2PBiblioteca);

        opcionP2PBusqueda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        opcionP2PBusqueda.setText("Nueva Búsqueda");
        opcionP2PBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionP2PBusquedaActionPerformed(evt);
            }
        });
        menuP2PSF.add(opcionP2PBusqueda);

        opcionP2PDescargas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        opcionP2PDescargas.setText("Mis descargas");
        opcionP2PDescargas.setToolTipText("Muestra todas las descargas realizadas");
        opcionP2PDescargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionP2PDescargasActionPerformed(evt);
            }
        });
        menuP2PSF.add(opcionP2PDescargas);
        menuP2PSF.add(separadorP2PSF);

        opcionP2PLimpiarResultados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        opcionP2PLimpiarResultados.setText("Limpiar Resultados");
        opcionP2PLimpiarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionP2PLimpiarResultadosActionPerformed(evt);
            }
        });
        menuP2PSF.add(opcionP2PLimpiarResultados);

        opcionP2PLimpiarDescargas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        opcionP2PLimpiarDescargas.setText("Limpiar Descargas");
        opcionP2PLimpiarDescargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionP2PLimpiarDescargasActionPerformed(evt);
            }
        });
        menuP2PSF.add(opcionP2PLimpiarDescargas);

        menuPpal.add(menuP2PSF);

        menuAyuda.setText("Ayuda");

        ayudaAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        ayudaAyuda.setText("Ayuda");
        ayudaAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaAyudaActionPerformed(evt);
            }
        });
        menuAyuda.add(ayudaAyuda);

        ayudaAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ayudaAcercaDe.setText("Acerca de...");
        ayudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(ayudaAcercaDe);

        menuPpal.add(menuAyuda);

        setJMenuBar(menuPpal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionArchivoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionArchivoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionArchivoLoginActionPerformed

    private void iconConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconConectarActionPerformed

    private void opcionArchivoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionArchivoLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionArchivoLogoutActionPerformed

    private void iconDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconDesconectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconDesconectarActionPerformed

    private void opcionP2PBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionP2PBibliotecaActionPerformed
        // Cunado se pulse dentro del menú en Mi Biblioteca se mostrará esta pestaña
        pestanyasApp.setSelectedIndex(0);
    }//GEN-LAST:event_opcionP2PBibliotecaActionPerformed

    private void opcionP2PBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionP2PBusquedaActionPerformed
        //
        pestanyasApp.setSelectedIndex(1);
    }//GEN-LAST:event_opcionP2PBusquedaActionPerformed

    private void opcionP2PDescargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionP2PDescargasActionPerformed
        //
        pestanyasApp.setSelectedIndex(2);
    }//GEN-LAST:event_opcionP2PDescargasActionPerformed

    private void opcionP2PLimpiarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionP2PLimpiarResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionP2PLimpiarResultadosActionPerformed

    private void iconLimpiarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconLimpiarResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconLimpiarResultadosActionPerformed

    private void iconDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconDescargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconDescargarActionPerformed

    private void opcionP2PLimpiarDescargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionP2PLimpiarDescargasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionP2PLimpiarDescargasActionPerformed

    private void iconLimpiarDescargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconLimpiarDescargasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconLimpiarDescargasActionPerformed

    private void ayudaAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaAyudaActionPerformed
        // Cuando se pulse sobre la ayuda se abre dicha ventana
        Ayuda a = new Ayuda(this, true); // La instanciamos. Será modal
        a.setVisible(true); // Y la mostramos
    }//GEN-LAST:event_ayudaAyudaActionPerformed

    private void ayudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaAcercaDeActionPerformed
        // Cuando se pulse sobre la ayuda se abre dicha ventana
        AcercaDe ad = new AcercaDe(this, true); // La instanciamos. Será modal
        ad.setVisible(true); // Y la mostramos
    }//GEN-LAST:event_ayudaAcercaDeActionPerformed

    private void iconAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconAyudaActionPerformed
        // Si se pulsa sobre el icono correspondiente, se llama a su función
        this.ayudaAyudaActionPerformed(evt);
    }//GEN-LAST:event_iconAyudaActionPerformed

    private void iconSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconSalirActionPerformed
        // Si ha pulsado sobre el icono de salir se llama a la función correspondiente
        this.opcionArchivoSalirActionPerformed(evt);
    }//GEN-LAST:event_iconSalirActionPerformed

    private void opcionArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionArchivoSalirActionPerformed
        // Cerramos la aplicación, pero antes son necesarios una serie de pasos
        // 1 - Decirle al coordinador que nos vamos


        // 2 - Cerrar la aplicación
        System.exit(0);
    }//GEN-LAST:event_opcionArchivoSalirActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // Cuando se pulse en el botón de buscar
        
        //loaderBuscando.revalidate();
        loaderBuscando.setVisible(true);
        hilo.start();

        //loaderBuscando.repaint();
        //this.repaint();
        
        System.out.println("Acabo de lanza el hilo 1");

        
        // Simulación de la búsqueda de archivos
/*        try {
            java.lang.Thread.sleep(5000);
        } catch (InterruptedException ex) {
            System.out.println("Excepcion: " + ex.toString());
        }
        */
/*        for(int i=0; i<10000; i++)
           System.out.println("Wueeeeeeeeeeeeeeeeeeee");
        System.out.println("------------------------------");
  */      
    //    hilo.parar();
//        loaderBuscando.setVisible(false);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void anyadirRecursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anyadirRecursoMouseClicked
        // Cuando se pulse en el botón Añadir Recurso
        int opc = 0;
        File [] ficheros;

        // Creamos una ventana para que el usuario escoja su(s) fichero(s)
        javax.swing.JFileChooser anyadir = new javax.swing.JFileChooser();
        anyadir.setMultiSelectionEnabled(true);
        anyadir.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);

        opc = anyadir.showOpenDialog(this); // Se muestra el diálogo


        //se crea un imagen a partir de una ruta absoluta del proyecto donde se encuentra la imagen fisica
        ImageIcon imagen = new ImageIcon(getClass().getResource("/gui/images/conectar.png"));
        

        //se inserta la imagen en el modelo
        modeloListaRecursos.addElement(imagen);



        // Ahora comprobamos si ha pulsado sobre aceptar
        if (opc == javax.swing.JFileChooser.APPROVE_OPTION) {
          // Si se ha pulsado, obtenemos la ruta absoluta al archivo
          //ficheros = new File[anyadir.getSelectedFiles().length];
          ficheros = anyadir.getSelectedFiles(); // Obtenemos los ficheros seleccionados
          for(int i=0; i<ficheros.length; i++) 
              modeloListaRecursos.addElement(ficheros[i].getPath());
        }
    }//GEN-LAST:event_anyadirRecursoMouseClicked

    private void quitarRecursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitarRecursoMouseClicked
        // Cuando se pulse en el botón eliminar Recurso

        // Obtenemos el indice que ocupan los elementos que se han seleccionado
        int [] indices = listaFicherosCompartidos.getSelectedIndices();

        // Si no hay ningun elemento seleccionado
        if(indices.length == 0)
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No ha seleccionado ningún elemento para eliminar");

        for(int i=indices.length - 1; i>=0; i--)
            modeloListaRecursos.removeElementAt(indices[i]);
    }//GEN-LAST:event_quitarRecursoMouseClicked

    private void actualizarBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarBibliotecaMouseClicked
        // Cuando se pulse sobre este botón, se reconstruye la biblioteca XML
        Biblioteca bib = new Biblioteca(); // Instanciamos el objeto Biblioteca

        bib.insertarNuevoArchivo("javiSensations.rar", "/home/javi/XXX", 17818813, 76618253, false, new long[2]);
        bib.insertarNuevoArchivo("FernandoIntimo.rar", "/home/fer/perversiones", 813286, 2523423, true, new long[2]);
        if(bib.guardarXML())
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡Archivo \"Mi Biblioteca.xml\" generado correctamente!");
        else
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al generar el archivo \"Mi Biblioteca.xml\"");
    }//GEN-LAST:event_actualizarBibliotecaMouseClicked

    /**
     * Función que carga en la aplicación todos los ficheros compartidos por el usuario
     */
    private void cargarBiblioteca() {
        ParserXML parser = new ParserXML("MiBiblioteca.xml");

        // Parseamos primero el archivo XML para obtener el arbol cargado en memoria
        parser.parsearArchivoXML();
        
        // Despues lo parseamos el arbol XML para extraer la informacion
        parser.parsearDocumento();

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteP2P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizarBiblioteca;
    private javax.swing.JLabel anyadirRecurso;
    private javax.swing.JMenuItem ayudaAcercaDe;
    private javax.swing.JMenuItem ayudaAyuda;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField cajaTextoNomFich;
    private javax.swing.JButton iconAyuda;
    private javax.swing.JButton iconConectar;
    private javax.swing.JButton iconDescargar;
    private javax.swing.JButton iconDesconectar;
    private javax.swing.JButton iconLimpiarDescargas;
    private javax.swing.JButton iconLimpiarResultados;
    private javax.swing.JButton iconSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFicheroBuscar;
    private javax.swing.JList listaFicherosCompartidos;
    private javax.swing.JLabel loaderBuscando;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuP2PSF;
    private javax.swing.JMenuBar menuPpal;
    private javax.swing.JMenuItem opcionArchivoLogin;
    private javax.swing.JMenuItem opcionArchivoLogout;
    private javax.swing.JMenuItem opcionArchivoSalir;
    private javax.swing.JMenuItem opcionP2PBiblioteca;
    private javax.swing.JMenuItem opcionP2PBusqueda;
    private javax.swing.JMenuItem opcionP2PDescargas;
    private javax.swing.JMenuItem opcionP2PLimpiarDescargas;
    private javax.swing.JMenuItem opcionP2PLimpiarResultados;
    private javax.swing.JPanel panelAniadirFichero;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelDescargas;
    private javax.swing.JPanel panelMiBiblio;
    private javax.swing.JPanel panelNuevaBusqueda;
    private javax.swing.JPanel panelPpal;
    private javax.swing.JPanel panelResultadosBusqueda;
    private javax.swing.JPanel pestaniaBiblioteca;
    private javax.swing.JPanel pestaniaDescargas;
    private javax.swing.JTabbedPane pestanyasApp;
    private javax.swing.JLabel quitarRecurso;
    private javax.swing.JScrollPane scrollPaneDescargas;
    private javax.swing.JScrollPane scrollPaneResultados;
    private javax.swing.JToolBar.Separator separador1;
    private javax.swing.JToolBar.Separator separador2;
    private javax.swing.JPopupMenu.Separator separadorArchivo;
    private javax.swing.JPopupMenu.Separator separadorP2PSF;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JTable tableDescargas;
    // End of variables declaration//GEN-END:variables

}
