/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Help.java
 *
 * Created on 26-abr-2010, 12:54:43
 */

package gui;

import javax.swing.JFrame;

/**
 *
 * @author sema
 */
public class Opciones extends javax.swing.JDialog {

    private ClienteP2P _interfaz;

    /** Creates new form Help */
    public Opciones(JFrame parent, ClienteP2P interfaz) {
        super(parent, true); // El true es para hacer modal a la ventana
        initComponents();

        // Centramos la ventana en la pantalla (Sólo por NetBeans)
        setLocationRelativeTo(null);

        _interfaz = interfaz; // Referencia al objeto interfaz gráfica
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloDialog = new javax.swing.JLabel();
        etiquetaConexMax = new javax.swing.JLabel();
        etiquetaTamBloque = new javax.swing.JLabel();
        cajaConexMax = new javax.swing.JTextField();
        cajaTamBloque = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        etiquetaIPServidor = new javax.swing.JLabel();
        cajaIPServidor = new javax.swing.JTextField();
        etiquetaIPCliente = new javax.swing.JLabel();
        cajaIPCliente = new javax.swing.JTextField();
        etiquetaPuerto = new javax.swing.JLabel();
        cajaPuerto = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ayuda de StickMotion");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tituloDialog.setText("Opciones configurables:");

        etiquetaConexMax.setText("Número máximo de conexiones simultáneas:");

        etiquetaTamBloque.setText("Tamaño de los bloques de petición de partes:");

        cajaConexMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cajaConexMax.setText("0");

        cajaTamBloque.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cajaTamBloque.setText("0");

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/ok.png"))); // NOI18N
        botonAceptar.setText("¡Aceptar!");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        etiquetaIPServidor.setText("Dirección IP del Servidor P2PSF");

        cajaIPServidor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cajaIPServidor.setText("0");

        etiquetaIPCliente.setText("Dirección IP del cliente P2PSF");

        cajaIPCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cajaIPCliente.setText("0");

        etiquetaPuerto.setText("Puerto a través del cual se va a conectar");

        cajaPuerto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cajaPuerto.setText("0");

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/noOk.png"))); // NOI18N
        botonCancelar.setText("¡Cancelar!");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloDialog)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(etiquetaTamBloque)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaTamBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(etiquetaConexMax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaConexMax))
                                    .addComponent(etiquetaIPServidor)
                                    .addComponent(etiquetaIPCliente)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(etiquetaPuerto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajaPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(botonAceptar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonCancelar))))))
                    .addComponent(cajaIPServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaIPCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaConexMax)
                    .addComponent(cajaConexMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTamBloque)
                    .addComponent(cajaTamBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaIPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaIPServidor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaIPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaIPCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPuerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * MÃ©todo que captura los valores introducidos y los devuelve a la interfaz
     * @param evt
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        int _tam = 0, _conex = 0;

        // Si es mayor que 0, devolvemos el valor
        if(Integer.parseInt(cajaTamBloque.getText()) > 0)
            _tam = Integer.parseInt(cajaTamBloque.getText());
        else
            _tam = 0;

        // Lo mismo con las conexiones mÃ¡ximas
        if(Integer.parseInt(cajaConexMax.getText()) > 0)
            _conex = Integer.parseInt(cajaConexMax.getText());
        else
            _conex = 0;

        _interfaz.establecerOpciones(_tam, _conex);
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * MÃ©todo que deja los valores intactos, es decir, ignora los cambios
     * introducidos en las cajas de texto
     * @param evt
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField cajaConexMax;
    private javax.swing.JTextField cajaIPCliente;
    private javax.swing.JTextField cajaIPServidor;
    private javax.swing.JTextField cajaPuerto;
    private javax.swing.JTextField cajaTamBloque;
    private javax.swing.JLabel etiquetaConexMax;
    private javax.swing.JLabel etiquetaIPCliente;
    private javax.swing.JLabel etiquetaIPServidor;
    private javax.swing.JLabel etiquetaPuerto;
    private javax.swing.JLabel etiquetaTamBloque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloDialog;
    // End of variables declaration//GEN-END:variables

}
