package cliente;


/**
* cliente/EstrArchivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 11 de mayo de 2010 21H59' CEST
*/

public final class EstrArchivo implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int tam = (int)0;
  public long checksum = (long)0;
  public boolean seed = false;

  public EstrArchivo ()
  {
  } // ctor

  public EstrArchivo (String _nombre, int _tam, long _checksum, boolean _seed)
  {
    nombre = _nombre;
    tam = _tam;
    checksum = _checksum;
    seed = _seed;
  } // ctor

} // class EstrArchivo
