package cliente;


/**
* cliente/infoArchivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 29 de mayo de 2010 12H39' CEST
*/

public final class infoArchivo implements org.omg.CORBA.portable.IDLEntity
{
  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public String ruta = null;
  public String nombre = null;
  public long tam = (long)0;
  public long checksum = (long)0;

  public infoArchivo ()
  {
  } // ctor

  public infoArchivo (String _ruta, String _nombre, long _tam, long _checksum)
  {
    ruta = _ruta;
    nombre = _nombre;
    tam = _tam;
    checksum = _checksum;
  } // ctor

} // class infoArchivo
