package cliente;


/**
* cliente/parteArchivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 14 de mayo de 2010 11H07' CEST
*/

public final class parteArchivo implements org.omg.CORBA.portable.IDLEntity
{
  public long inicio = (long)0;
  public long fin = (long)0;

  public parteArchivo ()
  {
  } // ctor

  public parteArchivo (long _inicio, long _fin)
  {
    inicio = _inicio;
    fin = _fin;
  } // ctor

} // class parteArchivo
