package cliente;

/**
* cliente/UsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 14 de mayo de 2010 11H07' CEST
*/

public final class UsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public cliente.Usuario value = null;

  public UsuarioHolder ()
  {
  }

  public UsuarioHolder (cliente.Usuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cliente.UsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cliente.UsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cliente.UsuarioHelper.type ();
  }

}
