package cliente;


/**
* cliente/UsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 24 de mayo de 2010 17H19' CEST
*/

public interface UsuarioOperations 
{
  int getId ();
  byte[] solicitarParte (String nombre, long inicio, long fin);
} // interface UsuarioOperations
