package cliente;


/**
* cliente/vPartesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 24 de mayo de 2010 17H42' CEST
*/

public final class vPartesHolder implements org.omg.CORBA.portable.Streamable
{
  public cliente.parteArchivo value[] = null;

  public vPartesHolder ()
  {
  }

  public vPartesHolder (cliente.parteArchivo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cliente.vPartesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cliente.vPartesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cliente.vPartesHelper.type ();
  }

}
