package cliente;


/**
* cliente/EstrArchivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 13 de mayo de 2010 17H56' CEST
*/

public final class EstrArchivo implements org.omg.CORBA.portable.IDLEntity
{
  public String ruta = null;
  public String nombre = null;
  public long tam = (long)0;
  public long checksum = (long)0;
  public long partes[] = null;

  public EstrArchivo ()
  {
  } // ctor

  public EstrArchivo (String _ruta, String _nombre, long _tam, long _checksum, long[] _partes)
  {
    ruta = _ruta;
    nombre = _nombre;
    tam = _tam;
    checksum = _checksum;
    partes = _partes;
  } // ctor

} // class EstrArchivo
