package cliente;


/**
* cliente/EstrArchivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 12 de mayo de 2010 13H29' CEST
*/

public final class EstrArchivo implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int tam = (int)0;
  public long checksum = (long)0;
  public long partes[] = null;

  public EstrArchivo ()
  {
  } // ctor

  public EstrArchivo (String _nombre, int _tam, long _checksum, long[] _partes)
  {
    nombre = _nombre;
    tam = _tam;
    checksum = _checksum;
    partes = _partes;
  } // ctor

} // class EstrArchivo
