package cliente;


/**
* cliente/UsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 13 de mayo de 2010 17H56' CEST
*/

public interface UsuarioOperations 
{
  String saluda ();
  byte[] solicitarParte (String nombre, long inicio, long fin);
} // interface UsuarioOperations
