package cliente;


/**
* cliente/UsuarioPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 15 de mayo de 2010 05H21' CEST
*/

public abstract class UsuarioPOA extends org.omg.PortableServer.Servant
 implements cliente.UsuarioOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("saluda", new java.lang.Integer (0));
    _methods.put ("solicitarParte", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cliente/Usuario/saluda
       {
         String $result = null;
         $result = this.saluda ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // cliente/Usuario/solicitarParte
       {
         String nombre = in.read_string ();
         long inicio = in.read_longlong ();
         long fin = in.read_longlong ();
         byte $result[] = null;
         $result = this.solicitarParte (nombre, inicio, fin);
         out = $rh.createReply();
         cliente.vByteHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cliente/Usuario:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Usuario _this() 
  {
    return UsuarioHelper.narrow(
    super._this_object());
  }

  public Usuario _this(org.omg.CORBA.ORB orb) 
  {
    return UsuarioHelper.narrow(
    super._this_object(orb));
  }


} // class UsuarioPOA
