package archivo;


/**
* archivo/archivosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 6 de mayo de 2010 14H48' CEST
*/


// Secuencia de archivos
abstract public class archivosHelper
{
  private static String  _id = "IDL:archivo/archivos:1.0";

  public static void insert (org.omg.CORBA.Any a, archivo.Archivo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static archivo.Archivo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = archivo.ArchivoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (archivo.archivosHelper.id (), "archivos", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static archivo.Archivo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    archivo.Archivo value[] = null;
    int _len0 = istream.read_long ();
    value = new archivo.Archivo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = archivo.ArchivoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, archivo.Archivo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      archivo.ArchivoHelper.write (ostream, value[_i0]);
  }

}
