package archivo;

/**
* archivo/ArchivoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 6 de mayo de 2010 14H48' CEST
*/

public final class ArchivoHolder implements org.omg.CORBA.portable.Streamable
{
  public archivo.Archivo value = null;

  public ArchivoHolder ()
  {
  }

  public ArchivoHolder (archivo.Archivo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = archivo.ArchivoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    archivo.ArchivoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return archivo.ArchivoHelper.type ();
  }

}
