package archivo;


/**
* archivo/archivosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 6 de mayo de 2010 14H48' CEST
*/


// Secuencia de archivos
public final class archivosHolder implements org.omg.CORBA.portable.Streamable
{
  public archivo.Archivo value[] = null;

  public archivosHolder ()
  {
  }

  public archivosHolder (archivo.Archivo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = archivo.archivosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    archivo.archivosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return archivo.archivosHelper.type ();
  }

}
