package coordinador;


/**
* coordinador/CoordinadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 29 de mayo de 2010 12H39' CEST
*/


// Sirviente que permite a los usuarios conectarse a la red, desconectarse y recuperar informacion sobre los archivos.
public interface CoordinadorOperations 
{
  int conectar (cliente.EstrArchivo[] eas, cliente.Usuario usuario);
  void desconectar (cliente.EstrArchivo[] eas, int idUsuario);
  void anyadirArchivos (cliente.EstrArchivo[] eas, int idUsuario);
  void eliminarArchivos (cliente.EstrArchivo[] eas, int idUsuario);
  coordinador.Archivo buscar (String nombre);
  cliente.Usuario getUsuario (int id);
} // interface CoordinadorOperations
