package coordinador;


/**
* coordinador/CoordinadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 6 de mayo de 2010 14H48' CEST
*/

public interface CoordinadorOperations 
{
  void login (archivo.Archivo[] as);
  void muestra ();
} // interface CoordinadorOperations
