package coordinador;


/**
* coordinador/CoordinadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 13 de mayo de 2010 17H56' CEST
*/

public interface CoordinadorOperations 
{
  int conectar (cliente.EstrArchivo[] eas, String usuario);
  void desconectar (cliente.EstrArchivo[] eas, int idUsuario);
  void anyadirArchivos (cliente.EstrArchivo[] eas, int idUsuario);
  void eliminarArchivos (cliente.EstrArchivo[] eas, int idUsuario);
  coordinador.Archivo buscar (String nombre);
  String getReferencia (int id);
} // interface CoordinadorOperations
