package coordinador;


/**
* coordinador/CoordinadorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 15 de mayo de 2010 05H21' CEST
*/

public abstract class CoordinadorPOA extends org.omg.PortableServer.Servant
 implements coordinador.CoordinadorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("conectar", new java.lang.Integer (0));
    _methods.put ("desconectar", new java.lang.Integer (1));
    _methods.put ("anyadirArchivos", new java.lang.Integer (2));
    _methods.put ("eliminarArchivos", new java.lang.Integer (3));
    _methods.put ("buscar", new java.lang.Integer (4));
    _methods.put ("getUsuario", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // coordinador/Coordinador/conectar
       {
         cliente.EstrArchivo eas[] = cliente.estrArchivosHelper.read (in);
         cliente.Usuario usuario = cliente.UsuarioHelper.read (in);
         int $result = (int)0;
         $result = this.conectar (eas, usuario);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // coordinador/Coordinador/desconectar
       {
         cliente.EstrArchivo eas[] = cliente.estrArchivosHelper.read (in);
         int idUsuario = in.read_long ();
         this.desconectar (eas, idUsuario);
         out = $rh.createReply();
         break;
       }

       case 2:  // coordinador/Coordinador/anyadirArchivos
       {
         cliente.EstrArchivo eas[] = cliente.estrArchivosHelper.read (in);
         int idUsuario = in.read_long ();
         this.anyadirArchivos (eas, idUsuario);
         out = $rh.createReply();
         break;
       }

       case 3:  // coordinador/Coordinador/eliminarArchivos
       {
         cliente.EstrArchivo eas[] = cliente.estrArchivosHelper.read (in);
         int idUsuario = in.read_long ();
         this.eliminarArchivos (eas, idUsuario);
         out = $rh.createReply();
         break;
       }

       case 4:  // coordinador/Coordinador/buscar
       {
         String nombre = in.read_string ();
         coordinador.Archivo $result = null;
         $result = this.buscar (nombre);
         out = $rh.createReply();
         coordinador.ArchivoHelper.write (out, $result);
         break;
       }

       case 5:  // coordinador/Coordinador/getUsuario
       {
         int id = in.read_long ();
         cliente.Usuario $result = null;
         $result = this.getUsuario (id);
         out = $rh.createReply();
         cliente.UsuarioHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:coordinador/Coordinador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Coordinador _this() 
  {
    return CoordinadorHelper.narrow(
    super._this_object());
  }

  public Coordinador _this(org.omg.CORBA.ORB orb) 
  {
    return CoordinadorHelper.narrow(
    super._this_object(orb));
  }


} // class CoordinadorPOA
