package coordinador;


/**
* coordinador/vStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* martes 11 de mayo de 2010 21H59' CEST
*/


//Definición de array de string
public final class vStringHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public vStringHolder ()
  {
  }

  public vStringHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = coordinador.vStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    coordinador.vStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return coordinador.vStringHelper.type ();
  }

}
