package archivo;


/**
* archivo/Archivo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 6 de mayo de 2010 14H48' CEST
*/

public final class Archivo implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int tam = (int)0;
  public long checksum = (long)0;

  public Archivo ()
  {
  } // ctor

  public Archivo (String _nombre, int _tam, long _checksum)
  {
    nombre = _nombre;
    tam = _tam;
    checksum = _checksum;
  } // ctor

} // class Archivo
